In [1]:
import numpy as np

In [2]:
a = np.array([[1,1], [0,0]])
np.linalg.svd(a)

(array([[1., 0.],
        [0., 1.]]),
 array([1.41421356, 0.        ]),
 array([[ 0.70710678,  0.70710678],
        [-0.70710678,  0.70710678]]))

In [11]:
import numpy as np
from time import time
n = 1000
m = np.random.random((n,n))
t = time()
eigvals, eigvecs = np.linalg.eig(m)
print(time() - t)

1.2707922458648682


In [4]:
from qat.lang.AQASM import *

In [21]:
prog = Program()
reg = prog.qalloc(1)
circ = prog.to_circ()

def f():
    prog = Program()
    reg = prog.qalloc(2)
    circ_f = prog.to_circ()
    %qatdisplay circ_f --svg
    return circ

f()

KeyError: 'circ_f'